### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by manuellemos** [phpearth/php-lands#10]

**Comment by manuellemos** [comment]
Testing

**Comment by nhlm** [comment]
I can confirm that you did a test, but we have no idea what exactly was the test. Not knowing what the test was, might run some of us insane.

Never mind.

**Comment by manuellemos** [comment]
Hello Matthias, sorry for not being specific. I just tested clicking a button on the PHP-lands page that got me here. It was just curiosity.

By the way, the maps look cool. It reminds me of the Lord of the rings. Congratulations for the hard work to the you and the PHP-Earth team.
